### ISSUE TITLE
windows-gaming should be a cargo workbench

### ISSUE THREAD

**Issue by Ediacarium** [main--/windows-gaming#110]
@oberien has already looked into this. This is especially relevant after #106 adds a second binary which we should be able to build with one call to cargo to simplify the makefile as @main-- already noted.

**Comment by oberien** [comment]
We need a virtual Cargo.toml in the repository root:
```toml
[workspace]
members = ["foo", "bar"]
```
In each member we need
```toml
[project]
workspace = ".."
```
i.e. the relative path to the virtual Cargo.toml.
Then we are able to use `cargo build -p <member>`, `cargo build --all` and `cargo run -p <member>`.
